[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "HfDfxyEvrXFuXbsM5A6WM75Vh196y8MnM8ZEcZcAE8h2"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
