[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "CzA626wF9ZKeGqyY1LgjUDc1BT5SFJp5qukjNm995Z8m"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
